id: "kafka-cluster"
kind: "List"
apiVersion: "v1"
name: "kafka-cluster"
description: "Creates Kafka Multi-Broker cluster"
items: 
- kind: "Service"
  apiVersion: "v1"
  metadata: 
    name: "kafka"
  spec: 
    ports: 
    - protocol: "TCP"
      port: 9092
      targetPort: "kafka-port"
    selector: 
      name: "kafka"
- kind: "ReplicationController"
  apiVersion: "v1"
  metadata: 
    name: "kafka"
    labels: 
      name: "kafka"
  spec: 
    replicas: 5
    selector: 
      name: "kafka"
    template: 
      metadata: 
        labels: 
          name: "kafka"
      spec: 
        volumes: 
        - name: "log"
          hostPath: 
            path: "/media/n/kafka/log"
        containers: 
        - name: "kafka"
          image: "dockerlab.int.thomsonreuters.com:30000/kafka"
          ports: 
          - name: "kafka-port"
            containerPort: 9092
            protocol: "TCP"
          env:
          - name: REFRESHED
            value: "true" 
          volumeMounts: 
          - name: "log"
            mountPath: "/kafka/log"
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
